export const resultList = [
  { n: "short" },
  { n: "shirts" },
  { n: "t-shirts" },
  //   { n: ["T-Shirts", "k", "l"] },
  //   { n: ["T-Shirts", "k", "l"] },
  //   { n: ["T-Shirts", "k", "l"] },
  //   { n: ["T-Shirts", "k", "l"] },
  //   { n: ["T-Shirts", "k", "l"] },
  //   { n: ["Shirts", "k", "l"] },
  //   { n: ["Shirts", "k", "l"] },
  //   { n: ["Shirts", "k", "l"] },
  //   { n: ["Shirts", "k", "l"] },
  //   { n: ["Shirts", "k", "l"] },
  //   { n: ["Shorts", "k", "l"] },
  //   { n: ["Shorts", "k", "l"] },
  //   { n: ["Shorts", "k", "l"] },
  //   { n: ["Shorts", "k", "l"] },
  //   { n: ["Shorts", "k", "l"] },
];      