import perfume1 from "../../../../assets/images/kids/perfume1.png";
import perfume2 from "../../../../assets/images/kids/perfume2.png";
import perfume3 from "../../../../assets/images/kids/perfume3.png";
import perfume4 from "../../../../assets/images/kids/perfume4.png";
import perfume5 from "../../../../assets/images/kids/perfume5.png";
import perfume6 from "../../../../assets/images/kids/perfume6.png";
import perfume7 from "../../../../assets/images/kids/perfume7.png";
import perfume8 from "../../../../assets/images/kids/perfume8.png";
import perfume9 from "../../../../assets/images/kids/perfume9.png";
import perfume10 from "../../../../assets/images/kids/perfume10.png";
import perfume11 from "../../../../assets/images/kids/perfume11.png";
import perfume12 from "../../../../assets/images/kids/perfume12.png";
import perfume13 from "../../../../assets/images/kids/perfume13.png";
import perfume14 from "../../../../assets/images/kids/perfume14.png";
import perfume15 from "../../../../assets/images/kids/perfume15.png";
import perfume16 from "../../../../assets/images/kids/perfume16.png";
import perfume17 from "../../../../assets/images/kids/perfume17.png";
import perfume18 from "../../../../assets/images/kids/perfume18.png";
import perfume19 from "../../../../assets/images/kids/perfume19.png";
import perfume20 from "../../../../assets/images/kids/perfume20.webp";

export const cytrusperfume = [
  {
    id: "perfume1",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "34.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume1,
    colorVariants: [],
    small: "true",
    availableQuantity: 32,
  },
  {
    id: "perfume2",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "29.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume2,
    colorVariants: [],
    small: "true",
    availableQuantity: 36,
  },
  {
    id: "perfume3",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "49.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume3,
    colorVariants: [],
    small: "true",
    availableQuantity: 12,
  },
  {
    id: "perfume4",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume4,
    colorVariants: [],
    small: "true",
    availableQuantity: 46,
  },
  {
    id: "perfume5",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "499.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume5,
    colorVariants: [],
    small: "true",
    availableQuantity: 2,
  },
  {
    id: "perfume6",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "199.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume6,
    colorVariants: [],
    small: "true",
    availableQuantity: 15,
  },
  {
    id: "perfume7",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "449.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume7,
    colorVariants: [],
    small: "true",
    availableQuantity: 10,
  },
  {
    id: "perfume8",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "99.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume8,
    colorVariants: [],
    small: "true",
    availableQuantity: 146,
  },
  {
    id: "perfume9",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "299.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume9,
    colorVariants: [],
    small: "true",
    availableQuantity: 232,
  },
  {
    id: "perfume10",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "149.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume10,
    colorVariants: [],
    small: "true",
    availableQuantity: 106,
  },
  {
    id: "perfume11",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "249.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume11,
    colorVariants: [],
    small: "true",
    availableQuantity: 132,
  },
  {
    id: "perfume12",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume12,
    colorVariants: [],
    small: "true",
    availableQuantity: 186,
  },
  {
    id: "perfume13",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume13,
    colorVariants: [],
    small: "true",
    availableQuantity: 289,
  },
  {
    id: "perfume14",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "79.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume14,
    colorVariants: [],
    small: "true",
    availableQuantity: 159,
  },
  {
    id: "perfume15",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume15,
    colorVariants: [],
    small: "true",
    availableQuantity: 400,
  },
  {
    id: "perfume16",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume16,
    colorVariants: [],
    small: "true",
    availableQuantity: 191,
  },
  {
    id: "perfume17",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "119.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume17,
    colorVariants: [],
    small: "true",
    availableQuantity: 889,
  },
  {
    id: "perfume18",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "139.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume18,
    colorVariants: [],
    small: "true",
    availableQuantity: 259,
  },
  {
    id: "perfume19",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume19,
    colorVariants: [],
    small: "true",
    availableQuantity: 420,
  },
  {
    id: "perfume20",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Floral Perfume", "Hushboy Atir", "Цветочные духи"],
    description: [
      "Floral Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Hushboy Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цветочные духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "169.99$",
    size: "200ml",
    scent: ["floral", "gull ifori", "Цветочные"],
    bg: perfume20,
    colorVariants: [],
    small: "true",
    availableQuantity: 136,
  },
];
