import narcotic1 from "../../../../assets/images/kids/narcotic1.webp";
import narcotic2 from "../../../../assets/images/kids/narcotic2.webp";
import narcotic3 from "../../../../assets/images/kids/narcotic3.webp";
import narcotic4 from "../../../../assets/images/kids/narcotic4.webp";
import narcotic5 from "../../../../assets/images/kids/narcotic5.png";
import narcotic6 from "../../../../assets/images/kids/narcotic6.webp";
import narcotic7 from "../../../../assets/images/kids/narcotic7.webp";
import narcotic8 from "../../../../assets/images/kids/narcotic8.webp";
import narcotic9 from "../../../../assets/images/kids/narcotic9.webp";
import narcotic10 from "../../../../assets/images/kids/narcotic10.png";
import narcotic11 from "../../../../assets/images/kids/narcotic11.png";
import narcotic12 from "../../../../assets/images/kids/narcotic12.webp";
import narcotic13 from "../../../../assets/images/kids/narcotic13.webp";
import narcotic14 from "../../../../assets/images/kids/narcotic14.png";
import narcotic15 from "../../../../assets/images/kids/narcotic15.png";
import narcotic16 from "../../../../assets/images/kids/narcotic16.webp";
import narcotic17 from "../../../../assets/images/kids/narcotic17.webp";
import narcotic18 from "../../../../assets/images/kids/narcotic18.webp";
import narcotic19 from "../../../../assets/images/kids/narcotic19.png";
import narcotic20 from "../../../../assets/images/kids/narcotic20.png";

export const narcoticperfume = [
  {
    id: "narcotic1",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "34.99$",
    scent: "narcotic",
    bg: narcotic1,
    colorVariants: [],
    small: "true",
    availableQuantity: 32,
  },
  {
    id: "narcotic2",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "29.99$",
    scent: "narcotic",
    bg: narcotic2,
    colorVariants: [],
    small: "true",
    availableQuantity: 36,
  },
  {
    id: "narcotic3",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "49.99$",
    scent: "narcotic",
    bg: narcotic3,
    colorVariants: [],
    small: "true",
    availableQuantity: 12,
  },
  {
    id: "narcotic4",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    scent: "narcotic",
    bg: narcotic4,
    colorVariants: [],
    small: "true",
    availableQuantity: 46,
  },
  {
    id: "narcotic5",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "499.99$",
    scent: "narcotic",
    bg: narcotic5,
    colorVariants: [],
    small: "true",
    availableQuantity: 2,
  },
  {
    id: "narcotic6",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "199.99$",
    scent: "narcotic",
    bg: narcotic6,
    colorVariants: [],
    small: "true",
    availableQuantity: 15,
  },
  {
    id: "narcotic7",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "449.99$",
    scent: "narcotic",
    bg: narcotic7,
    colorVariants: [],
    small: "true",
    availableQuantity: 10,
  },
  {
    id: "narcotic8",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "99.99$",
    scent: "narcotic",
    bg: narcotic8,
    colorVariants: [],
    small: "true",
    availableQuantity: 146,
  },
  {
    id: "narcotic9",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "299.99$",
    scent: "narcotic",
    bg: narcotic9,
    colorVariants: [],
    small: "true",
    availableQuantity: 232,
  },
  {
    id: "narcotic10",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "149.99$",
    scent: "narcotic",
    bg: narcotic10,
    colorVariants: [],
    small: "true",
    availableQuantity: 106,
  },
  {
    id: "narcotic11",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "249.99$",
    scent: "narcotic",
    bg: narcotic11,
    colorVariants: [],
    small: "true",
    availableQuantity: 132,
  },
  {
    id: "narcotic12",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    scent: "narcotic",
    bg: narcotic12,
    colorVariants: [],
    small: "true",
    availableQuantity: 186,
  },
  {
    id: "narcotic13",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    scent: "narcotic",
    bg: narcotic13,
    colorVariants: [],
    small: "true",
    availableQuantity: 289,
  },
  {
    id: "narcotic14",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "79.99$",
    scent: "narcotic",
    bg: narcotic14,
    colorVariants: [],
    small: "true",
    availableQuantity: 159,
  },
  {
    id: "narcotic15",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    scent: "narcotic",
    bg: narcotic15,
    colorVariants: [],
    small: "true",
    availableQuantity: 400,
  },
  {
    id: "narcotic16",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    scent: "narcotic",
    bg: narcotic16,
    colorVariants: [],
    small: "true",
    availableQuantity: 191,
  },
  {
    id: "narcotic17",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "119.99$",
    scent: "narcotic",
    bg: narcotic17,
    colorVariants: [],
    small: "true",
    availableQuantity: 889,
  },
  {
    id: "narcotic18",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "139.99$",
    scent: "narcotic",
    bg: narcotic18,
    colorVariants: [],
    small: "true",
    availableQuantity: 259,
  },
  {
    id: "narcotic19",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    scent: "narcotic",
    bg: narcotic19,
    colorVariants: [],
    small: "true",
    availableQuantity: 420,
  },
  {
    id: "narcotic20",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Narcotic Perfume", "Narkotik Atir", "Наркотические духи"],
    description: [
      "Narcotic Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Narkotik Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Наркотические духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "169.99$",
    scent: "narcotic",
    bg: narcotic20,
    colorVariants: [],
    small: "true",
    availableQuantity: 136,
  },
];
