import cytrus1 from "../../../../assets/images/kids/cytrus1.png";
import cytrus2 from "../../../../assets/images/kids/cytrus2.png";
import cytrus3 from "../../../../assets/images/kids/cytrus3.png";
import cytrus4 from "../../../../assets/images/kids/cytrus4.png";
import cytrus5 from "../../../../assets/images/kids/cytrus5.png";
import cytrus6 from "../../../../assets/images/kids/cytrus6.png";
import cytrus7 from "../../../../assets/images/kids/cytrus7.png";
import cytrus8 from "../../../../assets/images/kids/cytrus8.png";
import cytrus9 from "../../../../assets/images/kids/cytrus9.png";
import cytrus10 from "../../../../assets/images/kids/cytrus10.png";
import cytrus11 from "../../../../assets/images/kids/cytrus11.png";
import cytrus12 from "../../../../assets/images/kids/cytrus12.png";
import cytrus13 from "../../../../assets/images/kids/cytrus13.png";
import cytrus14 from "../../../../assets/images/kids/cytrus14.png";
import cytrus15 from "../../../../assets/images/kids/cytrus15.png";
import cytrus16 from "../../../../assets/images/kids/cytrus16.png";
import cytrus17 from "../../../../assets/images/kids/cytrus17.png";
import cytrus18 from "../../../../assets/images/kids/cytrus18.png";
import cytrus19 from "../../../../assets/images/kids/cytrus19.png";
import cytrus20 from "../../../../assets/images/kids/cytrus20.png";

export const perfumecollection = [
  {
    id: "cytrus1",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "34.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus1,
    colorVariants: [],
    small: "true",
    availableQuantity: 32,
  },
  {
    id: "cytrus2",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "29.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus2,
    colorVariants: [],
    small: "true",
    availableQuantity: 36,
  },
  {
    id: "cytrus3",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "49.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus3,
    colorVariants: [],
    small: "true",
    availableQuantity: 12,
  },
  {
    id: "cytrus4",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus4,
    colorVariants: [],
    small: "true",
    availableQuantity: 46,
  },
  {
    id: "cytrus5",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "499.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus5,
    colorVariants: [],
    small: "true",
    availableQuantity: 2,
  },
  {
    id: "cytrus6",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "199.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus6,
    colorVariants: [],
    small: "true",
    availableQuantity: 15,
  },
  {
    id: "cytrus7",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "449.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus7,
    colorVariants: [],
    small: "true",
    availableQuantity: 10,
  },
  {
    id: "cytrus8",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "99.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus8,
    colorVariants: [],
    small: "true",
    availableQuantity: 146,
  },
  {
    id: "cytrus9",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "299.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus9,
    colorVariants: [],
    small: "true",
    availableQuantity: 232,
  },
  {
    id: "cytrus10",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "149.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus10,
    colorVariants: [],
    small: "true",
    availableQuantity: 106,
  },
  {
    id: "cytrus11",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "249.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus11,
    colorVariants: [],
    small: "true",
    availableQuantity: 132,
  },
  {
    id: "cytrus12",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus12,
    colorVariants: [],
    small: "true",
    availableQuantity: 186,
  },
  {
    id: "cytrus13",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus13,
    colorVariants: [],
    small: "true",
    availableQuantity: 289,
  },
  {
    id: "cytrus14",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "79.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus14,
    colorVariants: [],
    small: "true",
    availableQuantity: 159,
  },
  {
    id: "cytrus15",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "89.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus15,
    colorVariants: [],
    small: "true",
    availableQuantity: 400,
  },
  {
    id: "cytrus16",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "69.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus16,
    colorVariants: [],
    small: "true",
    availableQuantity: 191,
  },
  {
    id: "cytrus17",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "119.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus17,
    colorVariants: [],
    small: "true",
    availableQuantity: 889,
  },
  {
    id: "cytrus18",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "139.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus18,
    colorVariants: [],
    small: "true",
    availableQuantity: 259,
  },
  {
    id: "cytrus19",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "59.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus19,
    colorVariants: [],
    small: "true",
    availableQuantity: 420,
  },
  {
    id: "cytrus20",
    gender: "perfume",
    e: ["perfume varieties", "atirlar hilmalligi", "pазновидность духов"],
    f: ["Cytrus Perfume", "Sitrus Atir", "Цитрусовые духи"],
    description: [
      "Cytrus Perfume is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Sitrus Atir hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Цитрусовые духи — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "169.99$",
    size: "200ml",
    scent: ["cytrus", "sitrus", "Цитрусовые"],
    bg: cytrus20,
    colorVariants: [],
    small: "true",
    availableQuantity: 136,
  },
];
