import kidsyellowtshirt from "../../../../assets/images/kids/kidsyellowtshirt.png";
import kidsgreentshirt from "../../../../assets/images/kids/kidsgreentshirt.png";
import kidsgreentshirt2 from "../../../../assets/images/kids/kidsgreentshirt2.png";
import kidswhitetshirt from "../../../../assets/images/kids/kidswhitetshirt.png";
import kidsblacktshirt from "../../../../assets/images/kids/kidsblacktshirt.png";
import kidsoinktshirt from "../../../../assets/images/kids/kidsoinktshirt.png";
import kidsredtshirt from "../../../../assets/images/kids/kidsredtshirt.png";
import kidsbluetshirt2 from "../../../../assets/images/kids/kidsbluetshirt2.png";
import kidsgreentshirt3 from "../../../../assets/images/kids/kidsgreentshirt3.png";
import kidsgreytshirt from "../../../../assets/images/kids/kidsgreytshirt.png";
import kidsgreypants from "../../../../assets/images/kids/kidsgreypants.png";
import kidsorangepants from "../../../../assets/images/kids/kidsorangepants.png";
import kidsgreypants2 from "../../../../assets/images/kids/kidsgreypants2.png";
import kidsbluepants from "../../../../assets/images/kids/kidsbluepants.png";
import kidsblackpants from "../../../../assets/images/kids/kidsblackpants.png";
import kidsbluechic from "../../../../assets/images/kids/kidsbluechic.png";
import kidsblueshort from "../../../../assets/images/kids/kidsblueshort.png";
import kidsbluejeans from "../../../../assets/images/kids/kidsbluejeans.png";
import kidsnavyshort from "../../../../assets/images/kids/kidsnavyshirt.png";
import kidspinkpants from "../../../../assets/images/kids/kidspinkpants.png";
import kidsredpants from "../../../../assets/images/kids/kidsredpants.png";
import kidswhitepants from "../../../../assets/images/kids/kidswhitepants.png";
import kidswhitetshirt2 from "../../../../assets/images/kids/kidswhitetshirt2.png";
import kidsbluepants2 from "../../../../assets/images/kids/kidsbluepants2.png";
import kidsgreypants3 from "../../../../assets/images/kids/kidsgreypants3.png";

export const casualkids = [
  {
    id: "kids1",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Yellow T-Shirt", "Sariq Futbolka", "Желтая футболка"],
    description: [
      "Kids Yellow T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Sariq Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Желтая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "s",
    color: "yellow",
    bg: kidsyellowtshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 1432,
  },
  {
    id: "kids2",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Green T-Shirt", "Yashil Futbolka", "Зеленая футболка"],
    description: [
      "Kids Green T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Yashil Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Зеленая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xs",
    color: "green",
    bg: kidsgreentshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 1597,
  },
  {
    id: "kids3",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Green T-Shirt", "Yashil Futbolka", "Зеленая футболка"],
    description: [
      "Kids Green T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Yashil Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Зеленая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "l",
    color: "green",
    bg: kidsgreentshirt2,
    colorVariants: [],
    small: "true",
    availableQuantity: 1806,
  },
  {
    id: "kids4",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids White T-Shirt", "Oq Futbolka", "Белая футболка"],
    description: [
      "Kids White T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Oq Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Белая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xl",
    color: "white",
    bg: kidswhitetshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 1206,
  },
  {
    id: "kids5",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Black T-Shirt", "Qora Futbolka", "Белая футболка"],
    description: [
      "Kids Black T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Qora Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Белая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xxl",
    color: "black",
    bg: kidsblacktshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 1006,
  },
  {
    id: "kids6",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Pink T-Shirt", "Pushti Futbolka", "Розовая футболка"],
    description: [
      "Kids Pink T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Pushti Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Розовая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "n",
    color: "pink",
    bg: kidsoinktshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 1314,
  },
  {
    id: "kids7",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Red T-Shirt", "Qizil Futbolka", "Красная футболка"],
    description: [
      "Kids Red T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Qizil Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Красная футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "s",
    color: "red",
    bg: kidsredtshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 314,
  },
  {
    id: "kids8",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Sky-Blue T-Shirt", "Havorang Futbolka", "Голубая футболка"],
    description: [
      "Kids Red T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Qizil Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Красная футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "n",
    color: "blue",
    bg: kidsbluetshirt2,
    colorVariants: [],
    small: "true",
    availableQuantity: 314,
  },
  {
    id: "kids9",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Green T-Shirt", "Yashil Futbolka", "Зеленая футболка"],
    description: [
      "Kids Green T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Yashil Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Зеленая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xs",
    color: "green",
    bg: kidsgreentshirt3,
    colorVariants: [],
    small: "true",
    availableQuantity: 597,
  },
  {
    id: "kids10",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Grey T-Shirt", "Kulrang Futbolka", "Серая футболка"],
    description: [
      "Kids Grey T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Kulrang Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Серая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xs",
    color: "grey",
    bg: kidsgreytshirt,
    colorVariants: [],
    small: "true",
    availableQuantity: 597,
  },
  {
    id: "kids11",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Grey Pants", "Kulrang Shalvar", "Серые Брюки"],
    description: [
      "Kids Grey Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Kulrang Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Серые Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "xs",
    color: "grey",
    bg: kidsgreypants,
    colorVariants: [],
    small: "true",
    availableQuantity: 397,
  },
  {
    id: "kids12",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Orange Pants", "Olovrang Shalvar", "Оранжевые Брюки"],
    description: [
      "Kids Orange Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Olovrang Kulrang Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Оранжевые Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "n",
    color: "orange",
    bg: kidsorangepants,
    colorVariants: [],
    small: "true",
    availableQuantity: 700,
  },
  {
    id: "kids13",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Grey Pants", "Kulrang Shalvar", "Серые Брюки"],
    description: [
      "Kids Grey Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Kulrang Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Серые Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "l",
    color: "grey",
    bg: kidsgreypants2,
    colorVariants: [],
    small: "true",
    availableQuantity: 197,
  },
  {
    id: "kids14",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Pants", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "xl",
    color: "blue",
    bg: kidsbluepants,
    colorVariants: [],
    small: "true",
    availableQuantity: 177,
  },
  {
    id: "kids15",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Black Pants", "Qora Shalvar", "Синий Брюки"],
    description: [
      "Kids Black Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Qora Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "xxl",
    color: "black",
    bg: kidsblackpants,
    colorVariants: [],
    small: "true",
    availableQuantity: 877,
  },
  {
    id: "kids16",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Chic", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "39.99$",
    size: "xs",
    color: "blue",
    bg: kidsbluechic,
    colorVariants: [],
    small: "true",
    availableQuantity: 77,
  },
  {
    id: "kids17",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Short", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "29.99$",
    size: "s",
    color: "blue",
    bg: kidsblueshort,
    colorVariants: [],
    small: "true",
    availableQuantity: 377,
  },
  {
    id: "kids18",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Short", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "37.99$",
    size: "n",
    color: "blue",
    bg: kidsbluejeans,
    colorVariants: [],
    small: "true",
    availableQuantity: 1377,
  },
  {
    id: "kids19",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Short", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "37.99$",
    size: "l",
    color: "blue",
    bg: kidsnavyshort,
    colorVariants: [],
    small: "true",
    availableQuantity: 1077,
  },
  {
    id: "kids20",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Pink Short", "Pushti Shalvar", "Розовый Брюки"],
    description: [
      "Kids Pink Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Pushti Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Розовый Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "57.99$",
    size: "xl",
    color: "pink",
    bg: kidspinkpants,
    colorVariants: [],
    small: "true",
    availableQuantity: 1077,
  },
  {
    id: "kids21",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Red Short", "Qizil Shalvar", "Красный Брюки"],
    description: [
      "Kids Red Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Qizil Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Красный Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "17.99$",
    size: "xxl",
    color: "red",
    bg: kidsredpants,
    colorVariants: [],
    small: "true",
    availableQuantity: 1077,
  },
  {
    id: "kids22",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids White Short", "Oq Shalvar", "Белый Брюки"],
    description: [
      "Kids White Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Oq Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Белый Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "17.99$",
    size: "xs",
    color: "white",
    bg: kidswhitepants,
    colorVariants: [],
    small: "true",
    availableQuantity: 877,
  },
  {
    id: "kids23",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids White T-Shirt", "Oq Futbolka", "Белая футболка"],
    description: [
      "Kids White T-Shirt is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Oq Futbolka hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Белая футболка — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "9.99$",
    size: "xxl",
    color: "white",
    bg: kidswhitetshirt2,
    colorVariants: [],
    small: "true",
    availableQuantity: 406,
  },
  {
    id: "kids24",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Blue Short", "To'q Ko'k Shalvar", "Синий Брюки"],
    description: [
      "Kids Blue Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar To'q Ko'k Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Синий Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "37.99$",
    size: "n",
    color: "blue",
    bg: kidsbluepants2,
    colorVariants: [],
    small: "true",
    availableQuantity: 1377,
  },
  {
    id: "kids25",
    gender: "kids",
    e: ["kid's clothing", "bolalar kiyimi", "детская одежда"],
    f: ["Kids Grey Pants", "Kulrang Shalvar", "Серые Брюки"],
    description: [
      "Kids Grey Pants is good choice for hot or warm up days like nowadays and only just for 39.99$. This for top part clothing can fit with any for bottom clohings and can make you look better in any event or place giving you an outstanding differece among many others. Hurry up only a few are available for this kind of super combo price. We have mainly this hijab in various color and size ranges so do not worry what you are looking for already is on the our stores.",
      "Bollalar Kulrang Shalvar hozirgi kabi issiq yoki isinish kunlari uchun yaxshi tanlovdir va atigi 39,99 dollarga. Bu kiyimning yuqori qismi uchun har qanday pastki kiyimlarga mos kelishi mumkin va sizni har qanday hodisa yoki joyda yaxshiroq ko'rinishga olib kelishi mumkin, bu sizga boshqalardan ajoyib farq qiladi. Shoshiling, bunday super kombinat narxiga faqat bir nechtasi mavjud. Bizda asosan bu hijob turli xil rang va o'lchamlarda mavjud, shuning uchun siz qidirayotgan narsangiz bizning do'konlarda allaqachon mavjud ekan, tashvishlanmang.",
      "Серые Брюки — хороший выбор для жарких или теплых дней, как сейчас, всего за 39,99 долларов. Эта одежда для верхней части может сочетаться с любой одеждой для нижней части и поможет вам выглядеть лучше на любом мероприятии или в любом месте, выделяя вас среди многих других. Спешите, по такой супер-комбо-цене доступно всего несколько экземпляров. В основном у нас есть хиджабы различных цветов и размеров, поэтому не волнуйтесь, то, что вы ищете, уже есть в наших магазинах.",
    ],
    s: "19.99$",
    size: "xs",
    color: "grey",
    bg: kidsgreypants3,
    colorVariants: [],
    small: "true",
    availableQuantity: 297,
  },
];
