export const ethictexts = [
  {
    t: [
      "Placing ethics at the heart of our business conduct is a powerful moral commitment, and the principle of trust is essential to the sustainable development of our business. This culture of integrity is of course based on compliance with laws and regulations, but equally on commitment to the values of the Group. It must be embodied by every one of Kering’s employees in their daily activities, whatever their nationality, location, position or seniority in the business.",
      "Ishbilarmonlik xulq-atvorimizning asosiga axloqni qo'yish kuchli ma'naviy majburiyatdir va ishonch tamoyili biznesimizning barqaror rivojlanishi uchun muhim ahamiyatga ega. Bunday halollik madaniyati, albatta, qonunlar va qoidalarga rioya qilishga asoslanadi, lekin bir xil darajada Guruh qadriyatlariga sodiqlikdir. Bu Keringning har bir xodimi tomonidan, millati, joylashuvi, lavozimi yoki biznesdagi stajidan qat'i nazar, kundalik faoliyatida mujassamlanishi kerak.",
      "Ставить этику в основу нашего делового поведения — это мощное моральное обязательство, а принцип доверия имеет важное значение для устойчивого развития нашего бизнеса. Эта культура честности, конечно же, основана на соблюдении законов и правил, но в равной степени и на приверженности ценностям Группы. Его должен воплощать каждый сотрудник Kering в своей повседневной деятельности, независимо от его национальности, местонахождения, должности или стажа в бизнесе.",
    ],
  },
  {
    t: [
      "Since 2018, when our Code of ethics replaced the Ethics Charter which we drew up in 2020, our Code of ethics has defined the major principles which frame and guide our daily actions. This Code provides a framework for what is expected from each of us in our professional activities, and when we are in contact with our employees, customers, shareholders and business partners. It also defines our commitment to the environment, which we are dedicated to protecting and on which we wish to minimize our impact, and to society at large, in which we intend to fully play our part as a good corporate citizen, engaged and responsible.",
      "2018-yildan boshlab, 2020-yilda biz ishlab chiqqan Axloq kodeksimiz o‘rniga Axloq kodeksimiz kundalik harakatlarimizni asoslaydigan va boshqaradigan asosiy tamoyillarni belgilab berdi. Ushbu Kodeks har birimizdan kasbiy faoliyatimizda, shuningdek, xodimlarimiz, mijozlarimiz, aktsiyadorlarimiz va biznes hamkorlarimiz bilan aloqada bo'lganimizda nima kutilishini ko'rsatadi. Shuningdek, u biz himoya qilishga bag'ishlangan va biz o'z ta'sirimizni minimallashtirishni istagan atrof-muhitga va umuman jamiyatga bo'lgan sadoqatimizni belgilaydi, bunda biz yaxshi korporativ fuqaro sifatida o'z rolimizni to'liq o'ynash niyatidamiz.",
      "С 2018 года, когда наш Кодекс этики заменил Хартию этики, которую мы разработали в 2020 году, наш Кодекс этики определил основные принципы, которые формируют и направляют наши повседневные действия. Этот Кодекс определяет рамки того, что ожидается от каждого из нас в нашей профессиональной деятельности и при контакте с нашими сотрудниками, клиентами, акционерами и деловыми партнерами. Это также определяет нашу приверженность окружающей среде, которую мы стремимся защищать и на которую мы хотим свести к минимуму наше воздействие, а также обществу в целом, в котором мы намерены в полной мере играть свою роль как добропорядочные, заинтересованные и ответственные корпоративные граждане.",
    ],
  },
  {
    t: [
      "This is the fourth edition of our Code of ethics since 2005 and it provides us with the  opportunity  to  restate  what  shapes  our ethical approach, at a time when our transformation into a pure player in the luxury sector has been achieved.The Code of ethics powerfully reaffirms our commitment to respect for human rights, not only for all our employees, but also for all those who work in our supply chains and contribute to our value creation. We mobilize all our energy and vigilance to combat child labor, forced labor, human trafficking and the exploitation of the most vulnerable groups, in particular migrants, as well as to combat all violence and discrimination, especially against women.",
      "Bu 2005-yildan buyon bizning axloq kodeksimizning to‘rtinchi nashri bo‘lib, u bizga lyuks sektorining sof o‘yinchisiga aylanishimizga erishilgan bir paytda bizning axloqiy yondashuvimizni shakllantirganini qayta ko‘rib chiqish imkoniyatini beradi. Axloq kodeksi kuchli nafaqat barcha xodimlarimiz, balki ta’minot zanjirlarimizda ishlayotgan va qadriyatlarimizni yaratishga hissa qo‘shayotgan barcha inson huquqlarini hurmat qilishga sodiqligimizni yana bir bor tasdiqlaydi. Biz barcha kuch va hushyorligimizni bolalar mehnati, majburiy mehnat, odam savdosi va aholining eng zaif qatlamlari, xususan, migrantlar ekspluatatsiyasiga qarshi kurashish, shuningdek, har qanday zo‘ravonlik va kamsitishlarga, ayniqsa, ayollarga qarshi kurashishga safarbar etamiz.",
      "Это четвертое издание нашего Кодекса этики с 2005 года, и оно дает нам возможность еще раз заявить, что формирует наш этический подход, в то время, когда мы превратились в чистого игрока в секторе роскоши. подтверждает нашу приверженность уважению прав человека не только для всех наших сотрудников, но и для всех тех, кто работает в наших цепочках поставок и вносит свой вклад в создание нашей ценности. Мы мобилизуем всю нашу энергию и бдительность для борьбы с детским и принудительным трудом, торговлей людьми и эксплуатацией наиболее уязвимых групп, в частности мигрантов, а также для борьбы со всем насилием и дискриминацией, особенно в отношении женщин.",
    ],
  },
  {
    t: [
      "This updated version also enables us to recall all the progress made in better preventing and detecting corruption and influence-peddling, in particular since 2015, the setting up of our Compliance Organization and the international network of Brand Compliance Officers within our Houses. They oversee strict compliance with all applicable laws and regulations in this area by defining the necessary policies and procedures, and supporting all our employees accordingly. We practice zero tolerance towards corruption, influence-peddling and any form of fraud, and it is vital that each and every one of us is aware of this.",
      "Ushbu yangilangan versiya, shuningdek, korruptsiya va ta'sir o'tkazishning oldini olish va aniqlashda erishilgan barcha yutuqlarni, xususan, 2015 yildan buyon, Muvofiqlik bo'yicha tashkilotimiz va uylarimizda Brendga muvofiqlik bo'yicha mutaxassislarning xalqaro tarmog'ini tashkil etishni eslash imkonini beradi. Ular ushbu sohadagi barcha amaldagi qonunlar va qoidalarga qat'iy rioya etilishini zarur siyosat va tartib-qoidalarni belgilash va shunga mos ravishda barcha xodimlarimizni qo'llab-quvvatlash orqali nazorat qiladi. Biz korruptsiyaga, ta'sir o'tkazishga va firibgarlikning har qanday ko'rinishiga nisbatan toqat qilmaymiz va har birimiz buni bilishimiz juda muhimdir.",
      "Эта обновленная версия также позволяет нам вспомнить весь прогресс, достигнутый в улучшении предотвращения и выявления коррупции и злоупотребления влиянием, в частности, с 2015 года, создания нашей Организации по обеспечению соответствия и международной сети сотрудников по обеспечению соответствия бренду в наших палатах. Они контролируют строгое соблюдение всех применимых законов и правил в этой области, определяя необходимые политики и процедуры и оказывая соответствующую поддержку всем нашим сотрудникам. Мы практикуем нулевую терпимость к коррупции, злоупотреблению влиянием и любым формам мошенничества, и очень важно, чтобы каждый из нас знал об этом.",
    ],
  },
  {
    t: [
      "Finally, it is particularly important to recall here that the ethical whistleblowing system that Kering set up several years ago, and which enables any individual to report a violation or suspected breach of our Code and its principles, is now available not only to Kering employees, but also to external and temporary staff working for the Group in all service providers and external partners with whom we have a contractual relationship. This mechanism is essential, and enables us to identify any possible shortcomings in adhering to our principles, as well as the remedial steps necessary. Protecting those who report such shortcomings to us selflessly, and in good faith, is an essential commitment throughout the Group.",
      "Va nihoyat, Kering tomonidan bir necha yil oldin o'rnatilgan va har qanday shaxsga bizning Kodeks va uning tamoyillari buzilgan yoki shubhali buzilganligi to'g'risida xabar berishga imkon beruvchi axloqiy ma'lumot tarqatish tizimi endilikda nafaqat Kering xodimlariga, shuningdek, barcha xizmat ko'rsatuvchi provayderlar va biz bilan shartnoma munosabatlari mavjud bo'lgan tashqi hamkorlarda Guruh uchun ishlaydigan tashqi va vaqtinchalik xodimlarga. Ushbu mexanizm juda muhim bo'lib, printsiplarimizga rioya qilishda yuzaga kelishi mumkin bo'lgan kamchiliklarni, shuningdek, zarur choralarni aniqlash imkonini beradi. Bunday kamchiliklar haqida bizga fidokorona va vijdonan xabar berganlarni himoya qilish butun Guruhning muhim majburiyatidir.",
      "Наконец, здесь особенно важно напомнить, что этическая система информирования о нарушениях, созданная компанией Kering несколько лет назад и позволяющая любому лицу сообщить о нарушении или подозрении на нарушение нашего Кодекса и его принципов, теперь доступна не только сотрудникам компании Kering. но также внешнему и временному персоналу, работающему в Группе у всех поставщиков услуг и внешних партнеров, с которыми у нас есть договорные отношения. Этот механизм имеет важное значение и позволяет нам выявлять любые возможные недостатки в соблюдении наших принципов, а также необходимые меры по их исправлению. Защита тех, кто самоотверженно и добросовестно сообщает нам о таких недостатках, является важным обязательством всей Группы.",
    ],
  },
  {
    t: [
      "This Code is a guide intended to provide a framework for all our activities, and to protect Kering, its success and longevity. I trust that you will familiarize yourself with it and apply it on a daily basis. Everything has been set up within the Group to support and help you fulfil this requirement; I am counting on you.",
      "Ushbu Kodeks barcha faoliyatimiz uchun asos yaratish va Keringni, uning muvaffaqiyati va uzoq umr ko'rishini himoya qilishga mo'ljallangan qo'llanmadir. Ishonamanki, siz u bilan tanishasiz va uni har kuni qo'llaysiz. Ushbu talabni bajarishingizni qo'llab-quvvatlash va yordam berish uchun Guruh ichida hamma narsa o'rnatilgan; Men senga ishonaman.",
      "Настоящий Кодекс представляет собой руководство, призванное обеспечить основу для всей нашей деятельности и защитить компанию Kering, ее успех и долголетие. Я надеюсь, что вы ознакомитесь с ним и будете применять его ежедневно. В Группе все создано для поддержки и помощи вам в выполнении этого требования; Я рассчитываю на тебя.",
    ],
  },
];