export const privacytext = [
  {
    t: [
      `This privacy policy covers situations where we, XON, access, collect, store process, use, disclose or transfer your personal information in paper or electronic form. It also covers situations where approved partners or other members of Kering use your personal information on our behalf. 
In some cases, other policies apply to you. It may be the case when you use certain products or services, and in this event: 
-	You will be notified of these other policies while using the products or services they apply to.
-	Such policies will supersede this privacy policy unless they expressly refer to it.
This privacy policy does not cover products or services you might use as provided by other companies acting on their own account.`,
      `Ushbu maxfiylik siyosati biz, XON, sizning shaxsiy ma'lumotlaringizga kirish, yig'ish, saqlash, qayta ishlash, foydalanish, oshkor qilish yoki qog'oz yoki elektron shaklda o'tkazish holatlarini qamrab oladi. Shuningdek, u tasdiqlangan hamkorlar yoki Keringning boshqa aʼzolari shaxsiy maʼlumotlaringizdan bizning nomimizdan foydalanishi holatlarini ham qamrab oladi. 
Ba'zi hollarda sizga nisbatan boshqa siyosatlar qo'llaniladi. Muayyan mahsulot yoki xizmatlardan foydalanganingizda va bu holatda: 
- Ular qo'llaniladigan mahsulot yoki xizmatlardan foydalanishda sizga ushbu boshqa siyosatlar haqida xabar beriladi.
- Bunday siyosatlar, agar ular to'g'ridan-to'g'ri murojaat qilmasa, ushbu maxfiylik siyosatini o'zgartiradi.
Ushbu maxfiylik siyosati siz foydalanishingiz mumkin bo'lgan mahsulotlar yoki xizmatlarni o'z hisobidan ishlaydigan boshqa kompaniyalar tomonidan taqdim etilganidek qamrab olmaydi.`,
      `Эта политика конфиденциальности охватывает ситуации, когда мы, XOH, получаем доступ, собираем, храним, обрабатываем, используем, раскрываем или передаем вашу личную информацию в бумажной или электронной форме. Он также охватывает ситуации, когда утвержденные партнеры или другие члены Kering используют вашу личную информацию от нашего имени. 
В некоторых случаях к вам применяются другие правила. Это может произойти, когда вы используете определенные продукты или услуги, и в этом случае: 
- Вы будете уведомлены об этих других политиках при использовании продуктов или услуг, к которым они применяются.
- Такие политики заменят настоящую политику конфиденциальности, если они прямо не ссылаются на нее.
Эта политика конфиденциальности не распространяется на продукты или услуги, которые вы можете использовать, предоставляемые другими компаниями, действующими от своего имени.`,
    ],
  },
  {
    t: [
      `Our privacy policy does not extend to services provided by other companies acting on their own account, such as franchisees and licensees or when you share information through social media (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram, etc.), or other online platforms owned and managed by other companies (Rakuten Advertising). These other companies have their own privacy policies in place, so remember that the way they use any personal information you give them will be subject to their rules and not ours.`,
      `Maxfiylik siyosatimiz franchayzi va litsenziat kabi oʻz hisobidan faoliyat yurituvchi boshqa kompaniyalar tomonidan taqdim etiladigan xizmatlarga yoki siz ijtimoiy tarmoqlar (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram va boshqalar) orqali maʼlumot almashishga taalluqli emas. , yoki boshqa kompaniyalarga tegishli va boshqariladigan boshqa onlayn platformalar (Rakuten Advertising). Bu boshqa kompaniyalar oʻzlarining maxfiylik siyosatlariga ega, shuning uchun siz ularga bergan har qanday shaxsiy maʼlumotlardan foydalanish usullari biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `Наша политика конфиденциальности не распространяется на услуги, предоставляемые другими компаниями, действующими от своего имени, например франчайзи и лицензиатов, или когда вы делитесь информацией через социальные сети (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram и т. д.). или другие онлайн-платформы, принадлежащие и управляемые другими компаниями (Rakuten Advertising). Эти другие компании имеют свои собственные политики конфиденциальности, поэтому помните, что то, как они используют любую личную информацию, которую вы им предоставляете, будет регулироваться их правилами, а не нашими.`,
    ],
  },
  {
    t: [
      `To be able to deliver our products and services to you, we need to share your personal information with approved partners or other members of Kering who generally act as our “data processors”. All are bound by an obligation to implement appropriate security measures to protect personal data in their possession, and are bound by a strict confidentiality agreement and specific contractual terms on “how” and “when” they are allowed to use your personal information on our behalf. 
Please be aware that certain approved partners, such as our franchisees and licensees or social media, could also determine “why” and “how” your personal information is used. They have their own privacy and cookies policies, so remember that the personal information you give them will be subject to their rules and not ours.`,
      `Sizga mahsulot va xizmatlarimizni yetkazib berish uchun shaxsiy maʼlumotlaringizni tasdiqlangan hamkorlar yoki Keringning boshqa aʼzolari bilan baham koʻrishimiz kerak, ular odatda bizning “maʼlumotlar protsessorimiz” vazifasini bajaradi. Ularning barchasi o'zlarida bo'lgan shaxsiy ma'lumotlarni himoya qilish uchun tegishli xavfsizlik choralarini qo'llash majburiyatini oladilar va qat'iy maxfiylik kelishuvi va shaxsiy ma'lumotlaringizdan bizning nomimizdan foydalanishga "qanday" va "qachon" ruxsat berilganligi to'g'risidagi maxsus shartnoma shartlari bilan bog'langan. . 
Iltimos, shuni yodda tutingki, bizning franchayzilarimiz va litsenziatlarimiz yoki ijtimoiy tarmoqlar kabi ma'lum tasdiqlangan hamkorlar sizning shaxsiy ma'lumotlaringizdan "nima uchun" va "qanday" foydalanilishini ham aniqlashi mumkin. Ularning shaxsiy maxfiylik va cookie-fayllar siyosati bor, shuning uchun siz ularga bergan shaxsiy maʼlumotlar biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `Чтобы иметь возможность предоставлять вам наши продукты и услуги, нам необходимо поделиться вашей личной информацией с утвержденными партнерами или другими членами Kering, которые обычно действуют как наши «обработчики данных». Все они обязаны принимать соответствующие меры безопасности для защиты находящихся в их распоряжении персональных данных, а также соблюдать строгое соглашение о конфиденциальности и конкретные договорные условия о том, «как» и «когда» им разрешено использовать вашу личную информацию от нашего имени. . 
Имейте в виду, что некоторые утвержденные партнеры, такие как наши франчайзи и лицензиаты или социальные сети, также могут определять, «почему» и «как» используется ваша личная информация. У них есть собственная политика конфиденциальности и использования файлов cookie, поэтому помните, что личная информация, которую вы им предоставляете, будет регулироваться их правилами, а не нашими.`,
    ],
  },
  {
    t: [
      `Certain specific information may be required to provide you with gift cards, customization services, or when you reserve a product or a service, request the repair of a product, or purchase products or services by phone, or on our website or a marketplace, including our restaurants’ bookings. In such cases, we could access, collect, store and use your personal information for delivery, warehouse and return management, or to register your table’s booking in one of our restaurants. During your visit to our store, we may need to collect your information in order to allow you to access our premises or when you wish to obtain a particular service: request for tax on products or in connection with our after-sales service, etc.`,
      `Maxfiylik siyosatimiz franchayzi va litsenziat kabi oʻz hisobidan faoliyat yurituvchi boshqa kompaniyalar tomonidan taqdim etiladigan xizmatlarga yoki siz ijtimoiy tarmoqlar (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram va boshqalar) orqali maʼlumot almashishga taalluqli emas. , yoki boshqa kompaniyalarga tegishli va boshqariladigan boshqa onlayn platformalar (Rakuten Advertising). Bu boshqa kompaniyalar oʻzlarining maxfiylik siyosatlariga ega, shuning uchun siz ularga bergan har qanday shaxsiy maʼlumotlardan foydalanish usullari biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `Определенная конкретная информация может потребоваться для предоставления вам подарочных карт, услуг по настройке или когда вы резервируете продукт или услугу, запрашиваете ремонт продукта или приобретаете продукты или услуги по телефону, на нашем веб-сайте или торговой площадке, в том числе заказы наших ресторанов. В таких случаях мы можем получить доступ, собирать, хранить и использовать вашу личную информацию для управления доставкой, складом и возвратом или для регистрации бронирования вашего столика в одном из наших ресторанов. Во время вашего посещения нашего магазина нам может потребоваться собрать вашу информацию, чтобы предоставить вам доступ к нашим помещениям или когда вы хотите получить определенную услугу: запрос налога на продукцию или в связи с нашим послепродажным обслуживанием и т. д.`,
    ],
  },
  {
    t: [
      `Once you have requested us to create your Gucci profile, via Gucci websites or any other means, including our customer service, your personal information will be linked to this profile, where we will keep all the information we have on you. This could include personal information we obtain directly from you as well as from other sources in accordance with applicable legislation. This could also include information about the purchases made when checking out as a guest or when checking out using a profile. The information in your Gucci profile is crucial to provide you with the Gucci personalized and tailored experience, and in some cases is necessary in order to access to some specific services or to purchase from our website, and thus it needs to be kept up to date for the best experience.`,
      `Maxfiylik siyosatimiz franchayzi va litsenziat kabi oʻz hisobidan faoliyat yurituvchi boshqa kompaniyalar tomonidan taqdim etiladigan xizmatlarga yoki siz ijtimoiy tarmoqlar (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram va boshqalar) orqali maʼlumot almashishga taalluqli emas. , yoki boshqa kompaniyalarga tegishli va boshqariladigan boshqa onlayn platformalar (Rakuten Advertising). Bu boshqa kompaniyalar oʻzlarining maxfiylik siyosatlariga ega, shuning uchun siz ularga bergan har qanday shaxsiy maʼlumotlardan foydalanish usullari biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `После того как вы попросите нас создать ваш профиль Gucci через веб-сайты Gucci или любым другим способом, включая нашу службу поддержки клиентов, ваша личная информация будет связана с этим профилем, где мы будем хранить всю имеющуюся у нас информацию о вас. Сюда может входить личная информация, которую мы получаем непосредственно от вас, а также из других источников в соответствии с применимым законодательством. Сюда также может входить информация о покупках, совершенных при оформлении заказа в качестве гостя или при оформлении заказа с использованием профиля. Информация в вашем профиле Gucci имеет решающее значение для предоставления вам персонализированного и индивидуального опыта Gucci, а в некоторых случаях необходима для доступа к некоторым конкретным услугам или совершения покупок на нашем веб-сайте, поэтому ее необходимо поддерживать в актуальном состоянии. для лучшего опыта.`,
    ],
  },
  {
    t: [
      `Once you have asked us to create your Gucci profile, we will supplement it with personal information such as your purchases, preferences and contact details. In this context, please be aware that we use personal identification information, such as your email address or phone number, to link an interaction or a purchase with your Gucci profile. This also applies when checking-out as a guest on our website when making a purchase, as mentioned above, or in case you bind your social media open ID account with your Gucci profile (by using dedicated QR Codes for example). In addition, we may use your date of birth to determine that you are old enough to use our services.`,
      `Maxfiylik siyosatimiz franchayzi va litsenziat kabi oʻz hisobidan faoliyat yurituvchi boshqa kompaniyalar tomonidan taqdim etiladigan xizmatlarga yoki siz ijtimoiy tarmoqlar (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram va boshqalar) orqali maʼlumot almashishga taalluqli emas. , yoki boshqa kompaniyalarga tegishli va boshqariladigan boshqa onlayn platformalar (Rakuten Advertising). Bu boshqa kompaniyalar oʻzlarining maxfiylik siyosatlariga ega, shuning uchun siz ularga bergan har qanday shaxsiy maʼlumotlardan foydalanish usullari biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `После того как вы попросите нас создать ваш профиль Gucci, мы дополним его личной информацией, такой как ваши покупки, предпочтения и контактные данные. В этом контексте имейте в виду, что мы используем личную идентификационную информацию, такую ​​как ваш адрес электронной почты или номер телефона, чтобы связать взаимодействие или покупку с вашим профилем Gucci. Это также применимо при оформлении заказа на нашем веб-сайте в качестве гостя, как упоминалось выше, или в случае, если вы привязываете свою учетную запись Open ID в социальной сети к своему профилю Gucci (например, с помощью специальных QR-кодов). Кроме того, мы можем использовать дату вашего рождения, чтобы определить, что вы достаточно взрослый, чтобы пользоваться нашими услугами.`,
    ],
  },
  {
    t: [
      `In order to keep your personal information accurate, we will take every reasonable step to ensure that personal information we hold is properly updated. Subject to your applicable privacy legislation you may have the right to have your information rectified at any time, and in any event please let us know if any of your information needs updating or correcting, and we will make our best efforts to detect and correct inaccurate personal information (data cleansing) and delete any duplicated dataset. This may require us to correct typographical errors or inconsistent personal information.`,
      `Maxfiylik siyosatimiz franchayzi va litsenziat kabi oʻz hisobidan faoliyat yurituvchi boshqa kompaniyalar tomonidan taqdim etiladigan xizmatlarga yoki siz ijtimoiy tarmoqlar (WeChat, WhatsApp, Baidu, Kakao Talk, Facebook, Twitter, Instagram va boshqalar) orqali maʼlumot almashishga taalluqli emas. , yoki boshqa kompaniyalarga tegishli va boshqariladigan boshqa onlayn platformalar (Rakuten Advertising). Bu boshqa kompaniyalar oʻzlarining maxfiylik siyosatlariga ega, shuning uchun siz ularga bergan har qanday shaxsiy maʼlumotlardan foydalanish usullari biznikiga emas, ularning qoidalariga boʻysunishini unutmang.`,
      `Чтобы обеспечить точность вашей личной информации, мы предпримем все разумные меры для обеспечения надлежащего обновления личной информации, которую мы храним. В соответствии с действующим законодательством о конфиденциальности вы можете иметь право на исправление вашей информации в любое время, и в любом случае сообщите нам, если какая-либо ваша информация нуждается в обновлении или исправлении, и мы приложим все усилия, чтобы обнаружить и исправить неточные сведения. личную информацию (очистка данных) и удалить любой дублированный набор данных. Это может потребовать от нас исправить опечатки или противоречивую личную информацию.`,
    ],
  },
];